In [17]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

from mlp import MLP
from loss import mse_loss

In [18]:
# Load the dataset
data = load_iris()

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.3, random_state=42)

# Convert the training and testing sets into input and labels
train_input = X_train
test_input = X_test

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both the training and testing data
train_input = scaler.fit_transform(train_input)
test_input = scaler.transform(test_input)


# One-hot encode the target labels
encoder = OneHotEncoder()
train_labels = encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
test_labels = encoder.transform(y_test.reshape(-1, 1)).toarray()

In [19]:
mlp = MLP(4, layer_dims = [64, 64, 3], activationfuncs=[ "relu", "softmax"], learning_rate=0.0004)

In [21]:
epoch=1000
batch_size = 1
for i in range(epoch):
    outs = []
    for j in range(0,len(train_input), batch_size):
        x = train_input[j:j+batch_size]
        y = train_labels[j:j+batch_size]
        out = mlp(x.T)
        mlp.backpropagation(y.T, out)
        outs.append(out)
    if i%10 == 0:
        print("mse loss : ", mse_loss(train_labels, np.array(outs).reshape([105,3])))

mse loss :  0.10159912732958372
mse loss :  0.10159863545111958
mse loss :  0.10159815099352716
mse loss :  0.1015976721476323
mse loss :  0.10159719706911101
mse loss :  0.10159672587513681
mse loss :  0.10159625575000998
mse loss :  0.10159578292195044
mse loss :  0.1015953048931716
mse loss :  0.10159481880370241
mse loss :  0.1015943213064165
mse loss :  0.10159380839881023
mse loss :  0.10159327519137738
mse loss :  0.10159271558132026
mse loss :  0.10159212178176193
mse loss :  0.10159148362458453
mse loss :  0.10159078749774965
mse loss :  0.10159001467134411
mse loss :  0.10158913855846659
mse loss :  0.10158812002756297
mse loss :  0.10158689893577212
mse loss :  0.10158537778991675
mse loss :  0.1015833874663431
mse loss :  0.10158060698092541
mse loss :  0.10157634529208978
mse loss :  0.1015688001541215
mse loss :  0.101551393265369
mse loss :  0.10146906990180067
mse loss :  0.08288624720338168
mse loss :  0.08263888770513587
mse loss :  0.08255641204754369
mse loss :  0.0

In [35]:
outs= []
for input, label in zip(train_input, y_train):
    out = mlp(input.reshape(4,1))
    outs.append(np.argmax(out))

In [36]:
np.array(outs).transpose()

array([1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1,
       2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0,
       1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1,
       2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0,
       2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 1, 0, 1, 2], dtype=int64)

In [37]:
y_train-outs

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
       -1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        0,  0,  0], dtype=int64)

In [64]:
outs= []
for input, label in zip(test_input, y_test):
    out = mlp(input.reshape(4,1))
    # print(out)
    outs.append(np.argmax(out))


y_test-outs

array([ 0,  0,  0,  0,  0,  0,  0,  1, -1,  0,  1,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0], dtype=int64)

In [44]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

# Load the wine dataset
data = load_wine()
X = data.data   # Features (inputs)
y = data.target # Target (outputs)

# Split the dataset into a training set and a test set
# test_size=0.2 means 20% of data is used for testing and 80% for training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Now, X_train and y_train are the training inputs and outputs,
# and X_test and y_test are the testing inputs and outputs.
train_input = X_train
test_input = X_test

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both the training and testing data
train_input = scaler.fit_transform(train_input)
test_input = scaler.transform(test_input)

# One-hot encode the target labels
encoder = OneHotEncoder()
train_labels = encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
test_labels = encoder.transform(y_test.reshape(-1, 1)).toarray()

print(train_labels.shape)

epoch=1000

# mlp = MLP(13, layer_dims = [128, 64, 3], activationfuncs=["softmax", "softmax"], learning_rate=0.05)
mlp = MLP(13, layer_dims = [128, 64, 3], activationfuncs=["softmax", "softmax"], learning_rate=0.005)


for i in range(epoch):
    outs = []
    for x, y in zip(train_input, train_labels):
        out = mlp(x.reshape(13,1))
        mlp.backpropagation(y.reshape(3,1), out)
        outs.append(out)
    if i%10 == 0:
        print("mse loss : ", mse_loss(train_labels, np.array(outs).reshape([142,3])))

outs= []
for input, label in zip(train_input, y_train):
    out = mlp(input.reshape(13,1))
    # print(out)
    outs.append(np.argmax(out))

(142, 3)
mse loss :  0.23055273508753207
mse loss :  0.22200764630136868
mse loss :  0.2158174880009909
mse loss :  0.21188971762936137
mse loss :  0.20959638888890297
mse loss :  0.20817012769486504
mse loss :  0.20711280812443603
mse loss :  0.2061849264087133
mse loss :  0.2052863884236396
mse loss :  0.20437646338107487
mse loss :  0.2034368928611217
mse loss :  0.2024573226314541
mse loss :  0.20142992448067673
mse loss :  0.20034744060915813
mse loss :  0.19920244029327533
mse loss :  0.1979869936057387
mse loss :  0.19669248755681598
mse loss :  0.1953094961499617
mse loss :  0.19382768217031868
mse loss :  0.19223573156082013
mse loss :  0.1905213282547835
mse loss :  0.18867118130285104
mse loss :  0.18667112780877496
mse loss :  0.1845063626873139
mse loss :  0.18216188716608062
mse loss :  0.1796233036514625
mse loss :  0.17687809038815783
mse loss :  0.17391745609864556
mse loss :  0.17073879702021127
mse loss :  0.16734858860242421
mse loss :  0.1637651244004797
mse loss :

In [45]:
np.array(outs).transpose()

array([2, 2, 1, 2, 1, 1, 1, 1, 2, 0, 1, 1, 2, 0, 1, 0, 0, 2, 2, 1, 1, 0,
       1, 0, 2, 1, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 1, 0, 2, 1, 0, 2, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 1, 1, 1, 2, 2, 0, 1, 2, 2, 1,
       0, 0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 0, 0, 1, 2, 2, 0, 1, 2, 2, 2, 2, 1,
       0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 1, 0, 2, 2, 0, 0, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 2, 0, 1, 1, 0, 1, 1], dtype=int64)

In [46]:
y_train-outs

array([ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0, -1, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0], dtype=int64)

In [47]:
outs= []
for input, label in zip(test_input, y_test):
    out = mlp(input.reshape(13,1))
    # print(out)
    outs.append(np.argmax(out))


y_test-outs

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0], dtype=int64)

In [48]:
def batch_normalization(batch, gamma, beta, epsilon=1e-5):
    # Calculate mean and variance
    mean = np.mean(batch, axis=0)
    variance = np.var(batch, axis=0)
    
    # Normalize
    batch_normalized = (batch - mean) / np.sqrt(variance + epsilon)
    
    # Scale and shift
    batch_scaled_and_shifted = gamma * batch_normalized + beta
    
    return batch_scaled_and_shifted