In [1]:
import numpy as np
import matplotlib as plt


In [499]:
inputs  = np.random.randn(4,1)
weights = np.random.randn(10,4)
biases  = np.random.randn(10,1)



In [512]:
x=weights.dot(inputs)+biases

x=x>0
x

array([[ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True]])

In [4]:
x.dot([2])

array([2, 2, 0, 0, 0, 2, 0, 2, 2, 2])

In [657]:
class Layer:
    def __init__(self,features,neurons,activationfunc):
        self.col                 = features
        self.weight              = np.random.randn(neurons,self.col)
        self.bias                = np.random.randn(neurons,1)
        self.input               = []
        self.output              = []
        self.output_activate     = []
        self.activationfunc      = activationfunc
        
    def feedforward(self,inputs):
        self.output              = self.weight.dot(inputs.transpose())+self.bias
        self.output_activate     = self.activationFunction(self.output)  
        return self.output_activate 
    
    def activationReLu(self,inputs):
        return np.maximum(inputs,0)
        
    def derivativeReLu(self,inputs):
        return inputs > 0
    
    def activationSoftMax(self,inputs):
        return np.exp(inputs)/np.sum(np.exp(inputs))
        
    def derivativeSofMax(self,inputs):
        return inputs*(1-inputs)
    
    def activationFunction(self,inputs):
        if self.activationfunc   == "relu":
            return self.activationReLu(inputs)
        elif self.activationfunc == "softmax":
            return self.activationSoftMax(inputs)
        else:
            return inputs
        
    
    def derivativeFunction(self):
        if self.activationfunc   == "relu":
            return self.derivativeReLu(self.output)
        elif self.activationfunc == "softmax":
            return self.derivativeSofMax(self.output_activate)
        else :
            return inputs
        
    def backpropagation(self,inputs):
        #derivative of loss for biases
        dEdB=inputs*self.derivativeFunction()
        
        #derivative of loss for weights
        dEdW=inputs*self.derivativeFunction()*self.input
        
        
        
        
        
        

In [658]:
layer  = Layer(4,10,"relu")
layer2 = Layer(10,10,"softmax")



In [660]:
out1  =  layer.feedforward(inputs.transpose())

out2  =  layer2.feedforward(out1.transpose())

layer2.backpropagation(out2)

ValueError: shapes (10,1) and (10,1) not aligned: 1 (dim 1) != 10 (dim 0)

array([ 2, 10, 18])